Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-467ca739 # Verificar na sua regiao
      Tags:
        - Key: Name
          Value: A simple example